spring:
  datasource:
    url: jdbc:mysql://localhost:3306/only-test
    username: root
    password: Cris1997
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop